### PR TITLE
Add jury data by season

### PR DESCRIPTION
**Pull request by davojta**
data for cpm_data jury for season 2015 - 2016

### CODE REVIEW

**Comment by staaas** [comment]
LGTM

**Review by staaas — APPROVED** [review]

**Comment by abitrolly** [comment]
Sorry for being late/offline. I like this goes on, but don't like that our dataset is being spread and mixed with Python code specific to our application. I still prefer to see CPM as data in `data/raw` so that people not familiar with Python/pip/Django/wagtail can discover and reuse it. Not only for analysis, but also for designing better access interfaces for users.

**Comment by staaas** [comment]
@abitrolly 

My strong opinion here is that primary data source is database. One might use API (end even export data to different locations) to get the most actual data.

The two main goals of these migrations:

* to migrate initial data
* to have production-like development environment

**Comment by abitrolly** [comment]
@nott the open data movement is all about making data free from restrictions of limited API and bugs of services providers, and given the chance to get rid of those restrictions, we instead prefer the same pattern, because... ? I am right to think that that's because of fears that:

1. datasets will get outdated

Which and why? For `which` let's separate `archive data` - what we are importing now, and `new festival data` and concentrate on `raw/data` to contain only the former for now. For `why` I don't expect past festivals data to be outdated.

2. database won't be used

Do we really want to working with past archive through admin interface? This is an unnecessary overhead to me, because it requires new level of indirection and more controls to keep users safe from accidentally editing data for the wrong year.

counter 1. "conway's law" or "getting one size that fits it all might be wrong"

I am more afraid that all festivals for all these years will look the same given the same database, design and handler classes, which is a shame for an art festival web site. I've seen your faces when you looked at the first version of site back few years ago. =) You need that flexibility to do static design without restrictions and limitations of jinja2/layout/template based sites. Most likely we will need to change not only the design, but the structure of the info, and the concept, and that DB structure would really be a hard limitation.

**Comment by davojta** [comment]
@abitrolly I think the one of the problem with current dataset is incomplete state of it. Most data has mined from google sheets and email subscription which contain notes and unstructured data.

And that dataset should be verified and finalized by editors who can use only cms tools for it.

I think after that verifying finished we can implement open data set delivery for future reuse.

For development purposes we working with current raw data sets copy to avoid random db state after release.

I think we should see open data set for other dev reuse as separate feature not as base one, because without visual editing tool we cant finished data verify from other team members.

**Comment by abitrolly** [comment]
Sounds reasonable. But it wouldn't be more effective if data verification process is exposed to everyone rather than to a limited set of editors who has access to admin interface? This requires a different strategy - an invitation to join and a public channel to report mistakes to quickly fix them.

It seems to me that we are waiting for data now before working on design, but the process could be made in parallel. In fact, design preview are ready. Maybe I need to write a tutorial for designers.

**Pull request merged**
