### PR TITLE
Add CPM logo to admin pages

### PR DESCRIPTION
**Pull request by abitrolly**
For details, see
http://docs.wagtail.io/en/latest/advanced_topics/customisation/branding.html

### CODE REVIEW

**Comment by staaas** [comment]
Favicon looks good.

I'd make logo white though:
screen shot 2016-08-04 at 15 05 38

**Comment by staaas** [comment]
@davojta what do you think?

**Comment by davojta** [comment]
LGTM

**Comment by staaas** [comment]
LGTM

**Pull request merged**
