### PR TITLE
Create .deploy/ space and move nginx config there

### PR DESCRIPTION
**Pull request by abitrolly**

### CODE REVIEW

**Comment by staaas** [comment]
@abitrolly can you briefly document your plan?
that will be easier to review prs having that in mind. we'll also be able to help with some steps if we understand your intensions.

**Comment by abitrolly** [comment]
@nott the plan for now is to move scripts related to deployment  into .deploy/ dir

**Comment by abitrolly** [comment]
This particular PR is needed to make nginx config readable.

**Comment by staaas** [comment]
i don't see much difference here

**Comment by abitrolly** [comment]
nginx config can be put into repo root, but there is already too much files irrelevant to Django application there.

**Comment by staaas** [comment]
@davojta what do you think?

**Comment by davojta** [comment]
I think move all deploy relate files to separate folder is good point. If it doent anything working right now.

**Comment by abitrolly** [comment]
I will get back to it in after 14th of December. Docker is awesome. @nott is there any tools to measure memory, CPU and disk space footprint of those containers? Ideally I want to run it and then freeze, and then get immediate and average values.

The point is to have bare minimum necessary for deployment in root, and move everything else to `.deploy`. This way I, as administrator, could get quick overview of deployment requirements without getting too deep into application structure.

**Comment by staaas** [comment]
@abitrolly I have plans to get rid of nginx and replace it with haproxy
let's close this pr

**Comment by abitrolly** [comment]
@nott I don't see how HAProxy is different from Nginx in this context. I want the ability to edit and copy [servers configs](https://github.com/kinaklub/next.filmfest.by/blob/950c8a434d98751ff883f9b26a975777b450cc89/Dockerfile-nginx) without Docker.

So if you agree that embedding config files for one app as strings into config files of other app is a bad pattern, let's discuss it further - where should we place your new HAProxy configs, so I can move current stuff there for now.

My problem with current solution "configs as Dockerfile stings" is that I can not read through quoted `\n` at line ends, and my syntax highlight doesn't work there.

**Comment by staaas** [comment]
@abitrolly 

I don't have strong opinion about place for configuration

* if they are small, I see many benefits in embedding them into Dockerfiles
* however I also see your concerns

We can just remove `production.yml` and `Dockerfile-nginx` for now.

**Pull request closed without merging**
