### PR TITLE
Add time table model and templates

### PR DESCRIPTION
**Pull request by staaas**
We still need to integrate time table into the old site.
But this is enough for populating the database on production.

@davojta could you please test it locally?

### CODE REVIEW

**Review by davojta — CHANGES_REQUESTED** [review]
Seems that after adding timetable page to homepage  page the link point to 404 page

Page not found (404)
Request Method:	GET
Request URL:	http://localhost:8000/en/admin/pages/add/events/timetable/3/
Raised by:	wagtail.wagtailcore.views.serve

**Comment by staaas** [comment]
@davojta could you please give more details where you've found the link? If you remove `en/` it should work fine.

**Comment by davojta** [comment]
Ive just added page to homepage as child page

**Review by davojta — APPROVED** [review]

**Comment by staaas** [comment]
Tested this together with @davojta - the app wasn't restarted properly and that was causing the issues.

**Pull request merged**
