### PR TITLE
Datacheck script

### PR DESCRIPTION
**Pull request by abitrolly**
`data/datacheck.py` script to help validating  #38 and other data inconsistencies, need #38 merged first (done) if decided to be added to repository.

### CODE REVIEW

**Comment by davojta** [comment]
LGTM. 
PS is that pr https://github.com/kinaklub/next.filmfest.by/pull/44 will work with that script ?

**Comment by abitrolly** [comment]
#44 won't work with that script, because the script expects flat data
structure. We may allow some data redundancy in the script and duplicate
partner data for over each year. This may be good if partner details change
from year to year.

We only need to agree how do we identify partners ourselves. Is it name,
URL or both, or maybe a logo?

**Comment by davojta** [comment]
I have changed structure to more flat view. Also added separate file with parners id. I think we can use name of the logo image file as partner id.

**Comment by abitrolly** [comment]
We can merge the script now and patch it later - `git bisect` helps to find offending commits - or I can do necessary changes directly in #44.

**Pull request merged**
