### PR TITLE
Results pages should be taking jury data from seasons

### PR DESCRIPTION
**Pull request by staaas**
* This fixes errors in jury members from cpm_data
* This also makes sure we take jury data for results from seasons
* And we also clear old jury data from results app

### CODE REVIEW

**Comment by staaas** [comment]
This is a dangerous PR, so manual testing is welcome.

**Comment by davojta** [comment]
I can test it today evening only. Is it okey @nott ?

**Comment by davojta** [comment]
Code seems okey

**Comment by staaas** [comment]
@davojta:
> I can test it today evening only. Is it okey @nott ?

sure

**Review by davojta — APPROVED** [review]

**Pull request merged**
